### PR TITLE
added punchline: 1 day to contribute to Open Source

### PR DESCRIPTION
**Pull request by hboutemy**
for people who won't immediately understand what's behind "Hack Commit Push" or "Hackergarten" terms

### CODE REVIEW

**Comment by fbiville** [comment]
I think we could actually replace the former headline `THE 1ST HACKERGARTEN CONFERENCE` with `1 FULL DAY TO DISCOVER HOW TO CONTRIBUTE TO OPEN SOURCE`.
Sadly, I don't think the word Hackergarten is fully understood by most of the people, hence the suggestion.
Or we could still mention it with something like:
`1 FULL HACKERGARTEN DAY TO CONTRIBUTE TO OPEN SOURCE`
What do you all think?

**Comment by aalmiray** [comment]
Hmm I like your first suggestion Florent :-)

**Comment by fbiville** [comment]
Alright, I'll update the PR and merge it tonight.

**Comment by fbiville** [comment]
Merged via d6f82540c1305d74807335c872fa97cdb485a4f0.

**Pull request closed without merging**
