### PR TITLE
Add projects

### PR DESCRIPTION
**Pull request by fbiville**

### CODE REVIEW

**Comment by fbiville** [comment]
I think I need early feedback on this. There could be A LOT of information we could display, but that will become super hard to read. Here what comes to mind:

 - project name + URL
 - project description (in FR / EN / both?)
 - project lead(s) (+ company?)
 - possible contributions
 - prerequisites

I think that's just too much to show.
What about keeping it to a minimum, i.e. name|URL + description and people will find out the rest when they come to the event? That's the current of the PR, please check it out.

WDYT @aalmiray @hboutemy @jexp?

Also, I picked some text for projects without any description, feel free to review it as well.

**Comment by hboutemy** [comment]
+1
possible contributions and prerequisites could eventually be on a popup: that's for a next step, the initial step here is perfect

**Review by hboutemy — APPROVED** [review]

**Comment by fbiville** [comment]
Project list is now up-to-date, I believe. Let me know what you think.

**Comment by fbiville** [comment]
Can you also make sure I did not mess up with the project lead names. Not sure about some projects.

**Pull request merged**
